SEASON_YEAR = 2024

BACKGROUND_COLOR = '#FFFFFF'
SECONDARY_COLOR = '#bf2420'
ACCENT_COLOR = '#eaeaea'
TEXT_COLOR_1 = '#000000'
TEXT_COLOR_2 = '#FFFFFF'
ROW_BACKGROUND_COLOR_1 = 'black'
ROW_BACKGROUND_COLOR_2 = 'red'
