# SEASON_YEAR = 2025
from datetime import datetime, timezone


SEASON_YEAR = datetime.now(timezone.utc).year
TEAM = 'Fairview High School'

WHITE_COLOR = '#ffffff'
BLACK_COLOR = '#000000'

# LIGHT MODE
BACKGROUND_COLOR = WHITE_COLOR
TEXT_COLOR_ONE = BLACK_COLOR
TEXT_COLOR_TWO = WHITE_COLOR
# Light palette
COLOR_ONE = '#bf2420'
COLOR_TWO = '#000000'
COLOR_THREE = '#8e94f2'
COLOR_FOUR = '#66a162'
COLOR_FIVE = '#a1d2ce'

# # Dark pallete
# COLOR_ONE = '#000000'
# COLOR_TWO = '#bf2420'
# COLOR_THREE = '#5ef38c'
# COLOR_FOUR = '#b7fdfe'
# COLOR_FIVE = '#bfd1e5'

# # DARK MODE
# BACKGROUND_COLOR = BLACK_COLOR
# TEXT_COLOR_ONE = WHITE_COLOR
# TEXT_COLOR_TWO = BLACK_COLOR
# # Light palette
# COLOR_ONE = '#83120f'
# COLOR_TWO = '#bf2420'
# COLOR_THREE = '#5ef38c'
# COLOR_FOUR = '#b7fdfe'
# COLOR_FIVE = '#bfd1e5'


MEN_COLOR = '#8f3528'
WOMEN_COLOR = '#1e8f89'

BODY_BACKGROUND_COLOR = BACKGROUND_COLOR
NAVIGATION_BACKGROUND_COLOR = COLOR_ONE
PRIMARY_SELECTION_COLOR = COLOR_THREE
SECONDARY_SELECTION_COLOR = COLOR_FOUR
TABLE_BACKGROUND_COLOR_ONE = COLOR_ONE
TABLE_BACKGROUND_COLOR_TWO = COLOR_TWO
TABLE_COLOR_ONE = WHITE_COLOR
CONTENT_COLOR_ONE = COLOR_FIVE
CONTENT_COLOR_TWO = COLOR_FOUR
